"""Validation tests for the isolated EU Data Act candidate builder."""

from __future__ import annotations

import json
from pathlib import Path
import tempfile
import unittest

from src.data_act_corpus import (
    DataActCandidateBuildError,
    build_data_act_candidate_records,
    parse_data_act_chunks,
    write_data_act_candidate_corpus,
)


PREPARED_DATA_ACT_SAMPLE = """
(12) Users should have access to data generated by connected products.

CHAPTER I

Article 2
Definitions

(5) ‘connected product’ means an item that obtains, generates or collects data.

(6) ‘related service’ means a digital service connected with the product.

CHAPTER II

Article 4
Rights and obligations of users and data holders

1. Data holders shall make readily available data accessible to the user.

(a) the data shall be provided without undue delay;

(b) the data shall be provided free of charge.

ANNEX III
Technical information
"""


class DataActSourceParsingTests(unittest.TestCase):
    def test_preserves_recital_article_definition_point_and_annex(self) -> None:
        chunks = parse_data_act_chunks(
            PREPARED_DATA_ACT_SAMPLE,
            source_name="EU Data Act Regulation 2023-2854.txt",
        )
        by_citation = {chunk["canonical_citation"]: chunk for chunk in chunks}

        self.assertIn("Recital 12", by_citation)
        self.assertIn("Article 2(5)", by_citation)
        self.assertIn("Article 2(6)", by_citation)
        self.assertIn("Article 4(1)", by_citation)
        self.assertIn("Article 4(1)(a)", by_citation)
        self.assertIn("Article 4(1)(b)", by_citation)
        self.assertIn("Annex III", by_citation)
        self.assertEqual(
            by_citation["Article 2(5)"]["definition_term"],
            "connected product",
        )
        self.assertEqual(
            by_citation["Article 4(1)(a)"]["parent_citation"],
            "Article 4(1)",
        )


class DataActCandidateBuildTests(unittest.TestCase):
    @staticmethod
    def _source(directory: str) -> Path:
        source = Path(directory) / "EU Data Act Regulation 2023-2854.txt"
        source.write_text(PREPARED_DATA_ACT_SAMPLE, encoding="utf-8")
        return source

    def test_candidate_records_have_complete_metadata_v2(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            records = build_data_act_candidate_records(self._source(directory))

        self.assertGreater(len(records), 0)
        for record in records:
            metadata = record["metadata"]
            self.assertEqual(record["id"], metadata["source_record_id"])
            self.assertEqual(metadata["metadata_schema_version"], "2.0.0")
            self.assertEqual(metadata["instrument_id"], "EU_DATA_ACT")
            self.assertEqual(
                metadata["document_version"],
                "Regulation (EU) 2023/2854",
            )
            self.assertEqual(
                metadata["authority_level"], "binding_legislation"
            )
            self.assertTrue(
                metadata["stable_evidence_id"].startswith("evidence:v2:")
            )

    def test_candidate_ids_are_stable_across_builds(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            source = self._source(directory)
            first = build_data_act_candidate_records(source)
            second = build_data_act_candidate_records(source)

        self.assertEqual(
            [record["id"] for record in first],
            [record["id"] for record in second],
        )
        self.assertEqual(
            [record["metadata"]["stable_evidence_id"] for record in first],
            [record["metadata"]["stable_evidence_id"] for record in second],
        )

    def test_candidate_writes_separate_json_artifact(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            source = self._source(directory)
            records = build_data_act_candidate_records(source)
            output = Path(directory) / "data-act-candidate.json"
            active_store = Path(directory) / "vector_store.json"
            active_store.write_text("legacy store", encoding="utf-8")

            written = write_data_act_candidate_corpus(
                records,
                output,
                existing_store_path=active_store,
            )

            self.assertEqual(json.loads(written.read_text()), records)
            self.assertEqual(active_store.read_text(), "legacy store")
            with self.assertRaises(DataActCandidateBuildError):
                write_data_act_candidate_corpus(
                    records,
                    active_store,
                    existing_store_path=active_store,
                )

    def test_non_catalogued_source_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / "unverified-data-act.txt"
            source.write_text(PREPARED_DATA_ACT_SAMPLE, encoding="utf-8")

            with self.assertRaises(DataActCandidateBuildError):
                build_data_act_candidate_records(source)


if __name__ == "__main__":
    unittest.main()
