"""Domain foundation for structured EU AI Act assessments."""

from src.assessment.case import (
    AssessmentCase,
    AssessmentCaseNotFoundError,
    AssessmentCaseSchemaMismatchError,
    AssessmentCaseService,
    DuplicateAssessmentCaseError,
)
from src.assessment.engine import AssessmentEngine, RuleOutputError
from src.assessment.evidence import (
    AuthorityLevel,
    DuplicateEvidenceError,
    Evidence,
    EvidenceService,
    EvidenceServiceResult,
    FindingEvidenceBinding,
    InMemoryEvidenceService,
    LegalEvidenceRetriever,
    VectorStoreFormatError,
    VectorStoreJSONEvidenceRetriever,
)
from src.assessment.facts import AssessmentFacts, ProductRegulationFacts
from src.assessment.findings import Finding, FindingCategory, FindingStatus, LegalBasis
from src.assessment.frameworks import RegulatoryFramework
from src.assessment.models import AssessmentRun, AssessmentRunStatus, TriState
from src.assessment.questionnaire import (
    AnswerType,
    DuplicateQuestionError,
    DuplicateQuestionFactPathError,
    InvalidQuestionFactPathError,
    Question,
    QuestionnaireEngine,
    QuestionnairePlan,
    QuestionNotFoundError,
    QuestionOption,
    QuestionRegistry,
)
from src.assessment.product_regulation import (
    AmbiguousAnnexIInstrumentAliasError,
    AnnexIInstrument,
    AnnexIInstrumentAliasNotFoundError,
    AnnexIInstrumentCatalog,
    AnnexIInstrumentCatalogError,
    AnnexIInstrumentNotFoundError,
    AnnexIInstrumentType,
    AnnexISection,
    InvalidProductRegulationFactsError,
    load_annex_i_instrument_catalog,
    validate_product_regulation_facts,
)
from src.assessment.requirements import (
    FactRequirementValidator,
    MissingFact,
    MissingFactReason,
    RuleRequirementResult,
)
from src.assessment.report import (
    AssessmentReport,
    FrameworkFindings,
    MissingInformation,
    ReportBuildError,
    ReportBuilder,
    RuleVersionMetadata,
)
from src.assessment.results import AssessmentResult, RuleExecutionFailure
from src.assessment.workflow import (
    AssessmentRunNotFoundError,
    AssessmentWorkflowService,
)

__all__ = [
    "AssessmentCase",
    "AssessmentCaseNotFoundError",
    "AssessmentCaseSchemaMismatchError",
    "AssessmentCaseService",
    "AssessmentEngine",
    "AssessmentFacts",
    "AssessmentResult",
    "AssessmentReport",
    "AssessmentRun",
    "AssessmentRunNotFoundError",
    "AssessmentRunStatus",
    "AssessmentWorkflowService",
    "AnswerType",
    "AmbiguousAnnexIInstrumentAliasError",
    "AnnexIInstrument",
    "AnnexIInstrumentAliasNotFoundError",
    "AnnexIInstrumentCatalog",
    "AnnexIInstrumentCatalogError",
    "AnnexIInstrumentNotFoundError",
    "AnnexIInstrumentType",
    "AnnexISection",
    "AuthorityLevel",
    "DuplicateEvidenceError",
    "DuplicateAssessmentCaseError",
    "DuplicateQuestionError",
    "DuplicateQuestionFactPathError",
    "Evidence",
    "EvidenceService",
    "EvidenceServiceResult",
    "FactRequirementValidator",
    "Finding",
    "FindingCategory",
    "FindingEvidenceBinding",
    "FindingStatus",
    "FrameworkFindings",
    "InMemoryEvidenceService",
    "InvalidQuestionFactPathError",
    "InvalidProductRegulationFactsError",
    "LegalEvidenceRetriever",
    "LegalBasis",
    "MissingFact",
    "MissingFactReason",
    "MissingInformation",
    "Question",
    "QuestionnaireEngine",
    "QuestionnairePlan",
    "QuestionNotFoundError",
    "QuestionOption",
    "QuestionRegistry",
    "ProductRegulationFacts",
    "RegulatoryFramework",
    "ReportBuildError",
    "ReportBuilder",
    "RuleExecutionFailure",
    "RuleOutputError",
    "RuleRequirementResult",
    "RuleVersionMetadata",
    "TriState",
    "VectorStoreFormatError",
    "VectorStoreJSONEvidenceRetriever",
    "load_annex_i_instrument_catalog",
    "validate_product_regulation_facts",
]
