"""Domain foundation for structured EU AI Act assessments."""

from src.assessment.case import (
    AssessmentCase,
    AssessmentCaseNotFoundError,
    AssessmentCaseSchemaMismatchError,
    AssessmentCaseService,
    DuplicateAssessmentCaseError,
)
from src.assessment.baselines import (
    AssessmentBaseline,
    EvidencePackBaseline,
    RuleBaselineEntry,
)
from src.assessment.context import (
    AssessmentContext,
    PrerequisiteFindingSummary,
)
from src.assessment.compatibility import (
    AssessmentFactsCompatibilityAdapter,
    AssessmentReportCompatibilityReader,
)
from src.assessment.engine import AssessmentEngine, RuleOutputError
from src.assessment.evidence import (
    AuthorityLevel,
    DuplicateEvidenceError,
    Evidence,
    EvidenceService,
    EvidenceServiceResult,
    FindingEvidenceBinding,
    InMemoryEvidenceService,
    LegalEvidenceRetriever,
    VectorStoreFormatError,
    VectorStoreJSONEvidenceRetriever,
)
from src.assessment.facts import AssessmentFacts, ProductRegulationFacts
from src.assessment.findings import Finding, FindingCategory, FindingStatus, LegalBasis
from src.assessment.frameworks import RegulatoryFramework
from src.assessment.fingerprints import V06FingerprintInput
from src.assessment.invocations import (
    AuthorizedRuleInvocation,
    RuleInvocation,
    derive_invocation_id,
)
from src.assessment.execution import RuleExecutionRecord, RuleExecutionStatus
from src.assessment.models import AssessmentRun, AssessmentRunStatus, TriState
from src.assessment.questionnaire import (
    AnswerType,
    DuplicateQuestionError,
    DuplicateQuestionFactPathError,
    InvalidQuestionFactPathError,
    Question,
    QuestionnaireEngine,
    QuestionnairePlan,
    QuestionNotFoundError,
    QuestionOption,
    QuestionRegistry,
)
from src.assessment.product_regulation import (
    AmbiguousAnnexIInstrumentAliasError,
    AnnexIInstrument,
    AnnexIInstrumentAliasNotFoundError,
    AnnexIInstrumentCatalog,
    AnnexIInstrumentCatalogError,
    AnnexIInstrumentNotFoundError,
    AnnexIInstrumentType,
    AnnexISection,
    InvalidProductRegulationFactsError,
    load_annex_i_instrument_catalog,
    validate_product_regulation_facts,
)
from src.assessment.requirements import (
    FactRequirementValidator,
    MissingFact,
    MissingFactReason,
    RuleRequirementResult,
)
from src.assessment.report import (
    ApplicabilityLimitation,
    AssessmentReport,
    FrameworkFindings,
    InformationalGap,
    MissingInformation,
    ReportBuildError,
    ReportBuilder,
    RuleVersionMetadata,
)
from src.assessment.recruitment_models import (
    ActorFacts,
    ActorKind,
    AISystemFacts,
    ArtefactSupplyState,
    ClassificationReviewState,
    ComplianceArtefactMetadata,
    ProcessingOperationFacts,
    RecruitmentDecisionProcessFacts,
    RecruitmentWorkflowFacts,
    RoleHypothesis,
    RoleHypothesisStatus,
    ScreeningCriterionFacts,
    TemporalContextFacts,
    TerritorialContextFacts,
)
from src.assessment.scope import (
    ActorId,
    AssessmentScope,
    InvocationId,
    ProcessingOperationId,
    StableIdentifier,
    SystemId,
    WorkflowId,
)
from src.assessment.results import AssessmentResult, RuleExecutionFailure
from src.assessment.rules import (
    RulePhase,
    RulePlanningError,
    RulePlanningMetadata,
    RulesetPlan,
)
from src.assessment.workflow import (
    AssessmentRunNotFoundError,
    AssessmentWorkflowService,
)

__all__ = [
    "AssessmentCase",
    "AssessmentCaseNotFoundError",
    "AssessmentCaseSchemaMismatchError",
    "AssessmentCaseService",
    "AssessmentEngine",
    "AssessmentBaseline",
    "AssessmentContext",
    "AssessmentFacts",
    "AssessmentFactsCompatibilityAdapter",
    "AssessmentResult",
    "AssessmentReport",
    "AssessmentReportCompatibilityReader",
    "AssessmentRun",
    "AssessmentRunNotFoundError",
    "AssessmentRunStatus",
    "AssessmentWorkflowService",
    "AssessmentScope",
    "ActorFacts",
    "ActorId",
    "ActorKind",
    "AISystemFacts",
    "ApplicabilityLimitation",
    "AnswerType",
    "AmbiguousAnnexIInstrumentAliasError",
    "AnnexIInstrument",
    "AnnexIInstrumentAliasNotFoundError",
    "AnnexIInstrumentCatalog",
    "AnnexIInstrumentCatalogError",
    "AnnexIInstrumentNotFoundError",
    "AnnexIInstrumentType",
    "AnnexISection",
    "AuthorityLevel",
    "AuthorizedRuleInvocation",
    "ArtefactSupplyState",
    "ClassificationReviewState",
    "ComplianceArtefactMetadata",
    "DuplicateEvidenceError",
    "DuplicateAssessmentCaseError",
    "DuplicateQuestionError",
    "DuplicateQuestionFactPathError",
    "Evidence",
    "EvidencePackBaseline",
    "EvidenceService",
    "EvidenceServiceResult",
    "FactRequirementValidator",
    "Finding",
    "FindingCategory",
    "FindingEvidenceBinding",
    "FindingStatus",
    "FrameworkFindings",
    "InformationalGap",
    "InvocationId",
    "InMemoryEvidenceService",
    "InvalidQuestionFactPathError",
    "InvalidProductRegulationFactsError",
    "LegalEvidenceRetriever",
    "LegalBasis",
    "MissingFact",
    "MissingFactReason",
    "MissingInformation",
    "Question",
    "QuestionnaireEngine",
    "QuestionnairePlan",
    "QuestionNotFoundError",
    "QuestionOption",
    "QuestionRegistry",
    "ProductRegulationFacts",
    "ProcessingOperationFacts",
    "ProcessingOperationId",
    "PrerequisiteFindingSummary",
    "RecruitmentDecisionProcessFacts",
    "RecruitmentWorkflowFacts",
    "RegulatoryFramework",
    "ReportBuildError",
    "ReportBuilder",
    "RoleHypothesis",
    "RoleHypothesisStatus",
    "RuleBaselineEntry",
    "RuleExecutionRecord",
    "RuleExecutionStatus",
    "RuleInvocation",
    "RuleExecutionFailure",
    "RuleOutputError",
    "RulePhase",
    "RulePlanningError",
    "RulePlanningMetadata",
    "RuleRequirementResult",
    "RuleVersionMetadata",
    "RulesetPlan",
    "TriState",
    "ScreeningCriterionFacts",
    "StableIdentifier",
    "SystemId",
    "TemporalContextFacts",
    "TerritorialContextFacts",
    "V06FingerprintInput",
    "VectorStoreFormatError",
    "VectorStoreJSONEvidenceRetriever",
    "load_annex_i_instrument_catalog",
    "validate_product_regulation_facts",
    "WorkflowId",
    "derive_invocation_id",
]
